# Generated by Django 4.2.1 on 2023-05-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('Phone_number', models.BigIntegerField()),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
